### ISSUE TITLE
Advanced Search Options for Persons

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-eXist-app#452]
Applies to all persons modules

Wild cards * and ? may be used to optimize search results. Wild cards may not be used at the beginning of a word, as it hinders search speed.

-box-
Search in Resource: [Radio buttons]: SBD (all entries), Qadishe (SBD Vol. I), Authors (SBD Vol. 2)
or
Search by Type: [Radio buttons]: all, saints, authors
-horizontal line-
Keyword: [Placeholder text] Any script (Syriac, Roman, etc.)
Person Name: [Placeholder text] Any script (Syriac, Roman, etc.)
-horizontal line-
Gregorian Date Range: [Start Date] [End Date]
Type of Date: all, birth, death, active (floruit), office, other
* Dates should be entered as YYYY or YYYY-MM-DD
Sex or Gender: [Dropdown]: all, female, male, eunuch, other
Limit to: [Dropdown] martyr, confession, office ```this may be multiple dropdowns, not sure```
-horizontal line-
Associated Places: (Should this be by Uri or place name?)
Associated Texts: * Enter syriaca uri. ex: http://syriaca.org/work/13
Related Persons: * Enter syriaca uri. ex: http://syriaca.org/person/13 (could this be by uri or by keyword?)

**Comment by davidamichelson** [comment]
Needs more work but this is a start

**Comment by wsalesky** [comment]
Titles and seriesStmt need to be added to SBD and authors data before the "Search in" will be functional.  
RE: #453

**Comment by wsalesky** [comment]
@davidamichelson  
Are there any relations currently in Qadishe? My search is not returning any.

**Comment by wsalesky** [comment]
@davidamichelson 
Can we clarify associated text? Is this searching for the name of a text in data/works? or a name in data/bibl, both?

Thanks!

**Comment by nathangibson** [comment]
@wsalesky I think the intention was for associated texts to be a place to search works (not bibls) that are related to a certain work. We *might* also want a place to search bibls, but that would be a separate field if so. Would need to discuss that with @davidamichelson. So far, the keyword search has been working just fine for me for searching bibls. (Sorry, I didn't realize I hadn't responded to this yesterday.)

**Comment by wsalesky** [comment]
@nathangibson Okay, thanks for the feedback!

**Comment by davidamichelson** [comment]
@nathangibson Will test and break

**Comment by nathangibson** [comment]
@wsalesky Here's what I have so far:

1. When I go to "SBD" and click on the advanced search gear, it does not automatically select the radio button "Search in Resource: SBD (all entries)"
2. Should a radio button be auto-selected for "Search by Type"? When I go to search it seems as if I have to click on something there, even though I don't. Perhaps  default could be "all". 
3. "Search by Type: All" gives 0 results. 

Also, maybe this should be in a separate issue, but I'm not sure the search is handling diacritics quite right. The issues I've noticed so far:
1. Diacritic + * = 0 results? Compare search for "Yaʿqōb" with search for "Yaʿqō*"
2. Halfring modifier letters: Maybe an indexing problem. I was under the impression that searches for "Yaqob" or "Ya'qob" should include all results for "Yaʿqob". However, the first two of those return 3 results, whereas the last returns 13.

**Comment by wsalesky** [comment]
Thanks! Keep them coming. 

(We do have a script to deal with the half-ring characters, looks like it is not running on the newest version of the data. I will have to take a look.)

**Comment by wsalesky** [comment]
@davidamichelson @nathangibson That reminds me, what is the difference between  the 
Search in Resource and the Search by Type options? I think the xquery would be exactly the same for them, as I currently understand the data model. Is that correct?

**Comment by nathangibson** [comment]
Great, that makes sense on the half-ring characters. 

So far as I understand it, the reason we have both "Search in Resource" and "Search by Type" is so that people can search for persons who are both authors and saints. So yes, the xQuery would be the same. Is that right @davidamichelson ?

**Comment by nathangibson** [comment]
Combining BC and AD dates in a single date range search returns only persons with BC dates. For example, searching -2000 to 2015 yields only 2 results. (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=&name=&start-date=-2000&end-date=2015&date-type=&gender=&state=&related-place=&place-type=&related-persons=&mentioned=) 

Also can we add the following to the help text under date range: "Add a minus sign (-) in front of BC dates." Plus a "more info" button or icon to http://syriaca.org/documentation/dates.html

**Comment by nathangibson** [comment]
Putting the same year in start date and end date does not yield any results. For example, Bar ʿEbroyo (http://syriaca.org/person/239) died in 1286, but searching for Start: 1286 End: 1286 gives 0 results (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=&name=&start-date=1286&end-date=1286&date-type=death&gender=&state=&related-place=&place-type=&related-persons=&mentioned=). However if I search for Start: 1285 End: 1287 I get him (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=&name=&start-date=1285&end-date=1287&date-type=death&gender=&state=&related-place=&place-type=&related-persons=&mentioned=)

**Comment by nathangibson** [comment]
Not getting date range search to work for Type: office. For example, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=&name=&start-date=0001&end-date=2015&date-type=office&gender=&state=&related-place=&place-type=&related-persons=&mentioned= should include Philoxenos of Mabbug (http://syriaca.org/person/44) but doesn't. Note that this is the element state type="office" with dates as from and to attributes.

**Comment by nathangibson** [comment]
Date range "other" is looking for events, correct? I don't get any hits on that, but I think it's because we don't have any dated events on persons yet.

**Comment by nathangibson** [comment]
Searching for Sex/Gender: "other" gives the following error:
exerr:ERROR Error while evaluating expression: collection('/db/apps/srophe-data/data/persons/tei')//tei:body[descendant::tei:sex/[@value != 'M' and @value != 'F' and @value != 'E']]. org.exist.xquery.XPathException: err:XPST0003 unexpected token: [ [at line 1, column 83]
 [at line 61, column 33]
In function:
	search:get-results(node(), map, xs:string?) [39:9:/db/apps/srophe/modules/search/search.xqm]
	templates:call-with-args(function, function*, element(), map) [208:13:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [277:13:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [462:17:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:surround(node(), map, xs:string, xs:string?, xs:string?, xs:string?) [39:9:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [131:51:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [88:9:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:apply(node()+, function, map?, map?) [50:5:/apps/apache-tomcat-7.0.54/webapps/exist/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
<img width="1287" alt="sex-other-error" src="https://cloud.githubusercontent.com/assets/3083452/11895282/c00afaf8-a57d-11e5-8b93-7857998223af.png">

**Comment by nathangibson** [comment]
@wsalesky @davidamichelson I think we need some adjustments to the "Limit to" option, which I'm afraid may require more discussion, but I'll give my opinionated suggestions here:

1. Change the name to "Other Characteristics". 
2. The drop-down values should be checkboxes, which should be relabeled 
 1. "is a martyr"
 2. "has a confession"
 3. "has an office"
 4. "has other characteristics".
3. Beside/below each checkbox should be a drop-down field labeled "of the type" that is only visible/active when one of these is selected. For example, "[has a confession] of the type [select]".
 1. Default value for this field is "any"
 2. Values for confessions drop-down are at http://syriaca.org/documentation/confessions.xml
 3. Values for offices drop-down are the ones contained in the role attribute. (We don't yet have an officially defined list, so far as I can remember.) 
 4. The field for "other characteristics" should be a free text field (not a drop-down).

My reasons for wanting to make these changes? 
A. To make these search options clearer to the users.
B. We want to be able to do searches as specific as "Show me a Syrian-Orthodox bishop who was a martyr."

**Comment by nathangibson** [comment]
Associated places is working great, even when I try using alternate names, wildcards, pasting in URIs, etc.

**Comment by nathangibson** [comment]
I believe the only person-person relationships we currently have are ones for disambiguation, such as 'different-from' or 'possibly-identical'. Still, I assume these should be returning hits for searches on "Related Persons", which they are not. For example, searching for "http://syriaca.org/person/1084" should return several hits including person/842 but it is not (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=&name=&start-date=&end-date=&date-type=&gender=&state=&related-place=&place-type=&related-persons=http%3A%2F%2Fsyriaca.org%2Fperson%2F1084&mentioned=). Even searching for "http://syriaca.org/person/*" gets me nothing.

**Comment by nathangibson** [comment]
Associated Texts search is mostly working great. The only problem I can find with it (hardly a high-priority fix) is that there's a weird issue with wildcards. It's as if the 1 character just before the wildcard is not being taken into account. E.g., searching for http://syriaca.org/work/* gives the same results as http://syriaca.org/work/1*. But I don't know of any use case where that would be a problem other than someone not being certain of the number of the text they're looking up.

**Comment by nathangibson** [comment]
@davidamichelson It occurs to me that, given the type of thing HMML is doing, we might want to have a way to search for a VIAF ID/URL. Currently if I put a VIAF URL in as a keyword search, I get nothing. However, if I search for just the numeric part of the ID, it does work. Would we want to make this functionality more explicit by putting in a VIAF ID/URL search box, for instance under "Person Name" and tweaking it to work for URLs as well?

**Comment by nathangibson** [comment]
OK, @wsalesky, that's all I can break! Thanks so much!

**Comment by wsalesky** [comment]
Thanks for the exhaustive testing @nathangibson! I will work though them next week.

**Comment by wsalesky** [comment]
Remaining issues: 
VIAF
bug in full text search for a url: ex: http://viaf.org/viaf/sourceID/SRP|person_308
Adjustments to "Limit to" options

**Comment by wsalesky** [comment]
@davidamichelson 
Should we add a search box for searching id/uris? For finding VIAF as well as Syriaca.org URIs?

**Comment by nathangibson** [comment]
@wsalesky 
1. Sorry for not replying to your comments! I need to adjust my mail settings b/c github messages are skipping the inbox.
2. I'll check the related persons a bit more but so far it's looking good.
3. I know we didn't get to discuss your questions today about the "Limit to" options. Anything you want me to respond to/clarify here?
Thanks!

**Comment by nathangibson** [comment]
Going to advanced search from SBD still does not automatically select the Search in Resource:
SBD (all entries) radio button.

**Comment by wsalesky** [comment]
@nathangibson 
No problem. I actually think we just need some feedback from @davidamichelson on the "Limit to" options ideas. 

Will be working through the new and improved bug list tomorrow, so feel free to add anything else you stumble upon to the list.

**Comment by nathangibson** [comment]
OK, sounds good. 
- Still having issues with date ranges that combine BC and AD. See, e.g, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?coll=sbd&type=&q=&name=&start-date=-0500&end-date=2015&date-type=&gender=&state=&related-place=&place-type=&related-persons=&mentioned=

**Comment by wsalesky** [comment]
Hum, I thought I fixed that... thanks.

**Comment by nathangibson** [comment]
- Issue of date range not including starting/ending year seems to be fixed. Also, I noticed you're automatically appending 0's to years that are less than 4 digits, which is great.

**Comment by nathangibson** [comment]
- Still having issues with date search of type "office". The following search should return Philoxenos of Mabbug (http://syriaca.org/person/44)  but does not: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?coll=sbd&type=&q=&name=&start-date=0450&end-date=0550&date-type=office&gender=&state=&related-place=&place-type=&related-persons=&mentioned=

**Comment by nathangibson** [comment]
- Gender = "other" issue is fixed

**Comment by nathangibson** [comment]
- I see that search for related persons can also take names and not just URIs. Nice!
- Interesting issue regarding "related persons" search. Searching for http://syriaca.org/person/1089 only yields http://syriaca.org/person/827, which is the only record linked directly from person/1089. However, person/827 lists both person/999 and person/1089. So should person/999 also be showing up? (And I need to make sure we keep our relations up to date!)

**Comment by wsalesky** [comment]
Escaping for astrix seems to have caused issues with wildcards in searches.

**Comment by wsalesky** [comment]
New bugs discovered in search. 
'n/a' is not being escaped properly.

**Comment by wsalesky** [comment]
Can now search for 'n/a' but relevance is poor.
