### ISSUE TITLE
Bug in relationship

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-eXist-app#726]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/410

**Comment by wsalesky** [comment]
Resolved when missing persons data was uploaded.

**Comment by davidamichelson** [comment]
Just an FYI, as of yesterday JN thought that some persons were still missing.

**Comment by wsalesky** [comment]
I uploaded the new data at around 10 or 11 last night. Let me know if there are still problems. All of the reported missing records are now showing up for me.
