### ISSUE TITLE
Tweak additions/corrections form to go to correct module editors

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#797]
When I tested submitting a correction on an authors record, @tacarlson received the notification and I didn't. After you get back, @wsalesky , can we make sure these forms go to the module editors? Thanks!

**Comment by davidamichelson** [comment]
I think there is already an issue for this and @tacarlson has kindly agreed to put up with this until we fix it. Not in this issue but offline I will send Winona a list of email addresses

**Comment by wsalesky** [comment]
@davidamichelson I can work on this when ever you send me the list.

**Comment by jsaintlauren** [comment]
Hi, all.  I wanted you to see the nice note that the Theology librarian
Rose Trupiano sent me after reviewing syriaca.org.  Hurray!

Hello Jeanne-Nicole,

Thank you for the info regarding your Syriac databases.  I have been adding
them to the list of Theology databases and have been looking through them.
These are amazing!  The information provided is very detailed as are the
 links to various resources (Clavis Patrum Graecorum, Worldcat, Zotero
database, Gazetteer, Internet Archive Books, etc.)

Not only is the content valuable but the interface is intuitive and
aesthetically pleasing and the Syriac text in the records is seamless.
Congratulations on the completion of and  launching these databases!

**Comment by wsalesky** [comment]
Okay, I think this has been corrected. Please contact me if you get any incorrect emails. 
Thanks for your patience while I tested.

**Comment by tacarlson** [comment]
I still received the persons emails of 10:56am, 11:00am, and 11:05am (as well as the place email of 11:03am, which is correct).  I don't think I should receive the persons emails.

________________________________

**Comment by wsalesky** [comment]
@tacarlson thanks for the info, you should not be receiving the persons emails. Let me do some more tweaking. I will be sending out one for BHSE and Works Cited in the next hour, please let me know if you receive those.

**Comment by wsalesky** [comment]
Okay, I think I have this sorted out now.
